/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApoioEmpresasBragaRouteImport } from './routes/apoio-empresas-braga'
import { Route as DesignEPresencaDigitalBragaRouteImport } from './routes/design-e-presenca-digital-braga'
import { Route as RedesWifiBragaRouteImport } from './routes/redes-wifi-braga'
import { Route as ReparacaoComputadoresBragaRouteImport } from './routes/reparacao-computadores-braga'
import { Route as ReparacaoHardwareBragaRouteImport } from './routes/reparacao-hardware-braga'
import { Route as ReparacaoPortateisBragaRouteImport } from './routes/reparacao-portateis-braga'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoioEmpresasBragaRoute = ApoioEmpresasBragaRouteImport.update({
  id: '/apoio-empresas-braga',
  path: '/apoio-empresas-braga',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignEPresencaDigitalBragaRoute =
  DesignEPresencaDigitalBragaRouteImport.update({
    id: '/design-e-presenca-digital-braga',
    path: '/design-e-presenca-digital-braga',
    getParentRoute: () => rootRouteImport,
  } as any)
const RedesWifiBragaRoute = RedesWifiBragaRouteImport.update({
  id: '/redes-wifi-braga',
  path: '/redes-wifi-braga',
  getParentRoute: () => rootRouteImport,
} as any)
const ReparacaoComputadoresBragaRoute =
  ReparacaoComputadoresBragaRouteImport.update({
    id: '/reparacao-computadores-braga',
    path: '/reparacao-computadores-braga',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReparacaoHardwareBragaRoute = ReparacaoHardwareBragaRouteImport.update({
  id: '/reparacao-hardware-braga',
  path: '/reparacao-hardware-braga',
  getParentRoute: () => rootRouteImport,
} as any)
const ReparacaoPortateisBragaRoute = ReparacaoPortateisBragaRouteImport.update({
  id: '/reparacao-portateis-braga',
  path: '/reparacao-portateis-braga',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apoio-empresas-braga': typeof ApoioEmpresasBragaRoute
  '/design-e-presenca-digital-braga': typeof DesignEPresencaDigitalBragaRoute
  '/redes-wifi-braga': typeof RedesWifiBragaRoute
  '/reparacao-computadores-braga': typeof ReparacaoComputadoresBragaRoute
  '/reparacao-hardware-braga': typeof ReparacaoHardwareBragaRoute
  '/reparacao-portateis-braga': typeof ReparacaoPortateisBragaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apoio-empresas-braga': typeof ApoioEmpresasBragaRoute
  '/design-e-presenca-digital-braga': typeof DesignEPresencaDigitalBragaRoute
  '/redes-wifi-braga': typeof RedesWifiBragaRoute
  '/reparacao-computadores-braga': typeof ReparacaoComputadoresBragaRoute
  '/reparacao-hardware-braga': typeof ReparacaoHardwareBragaRoute
  '/reparacao-portateis-braga': typeof ReparacaoPortateisBragaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apoio-empresas-braga': typeof ApoioEmpresasBragaRoute
  '/design-e-presenca-digital-braga': typeof DesignEPresencaDigitalBragaRoute
  '/redes-wifi-braga': typeof RedesWifiBragaRoute
  '/reparacao-computadores-braga': typeof ReparacaoComputadoresBragaRoute
  '/reparacao-hardware-braga': typeof ReparacaoHardwareBragaRoute
  '/reparacao-portateis-braga': typeof ReparacaoPortateisBragaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apoio-empresas-braga'
    | '/design-e-presenca-digital-braga'
    | '/redes-wifi-braga'
    | '/reparacao-computadores-braga'
    | '/reparacao-hardware-braga'
    | '/reparacao-portateis-braga'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apoio-empresas-braga'
    | '/design-e-presenca-digital-braga'
    | '/redes-wifi-braga'
    | '/reparacao-computadores-braga'
    | '/reparacao-hardware-braga'
    | '/reparacao-portateis-braga'
  id:
    | '__root__'
    | '/'
    | '/apoio-empresas-braga'
    | '/design-e-presenca-digital-braga'
    | '/redes-wifi-braga'
    | '/reparacao-computadores-braga'
    | '/reparacao-hardware-braga'
    | '/reparacao-portateis-braga'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApoioEmpresasBragaRoute: typeof ApoioEmpresasBragaRoute
  DesignEPresencaDigitalBragaRoute: typeof DesignEPresencaDigitalBragaRoute
  RedesWifiBragaRoute: typeof RedesWifiBragaRoute
  ReparacaoComputadoresBragaRoute: typeof ReparacaoComputadoresBragaRoute
  ReparacaoHardwareBragaRoute: typeof ReparacaoHardwareBragaRoute
  ReparacaoPortateisBragaRoute: typeof ReparacaoPortateisBragaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoio-empresas-braga': {
      id: '/apoio-empresas-braga'
      path: '/apoio-empresas-braga'
      fullPath: '/apoio-empresas-braga'
      preLoaderRoute: typeof ApoioEmpresasBragaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-e-presenca-digital-braga': {
      id: '/design-e-presenca-digital-braga'
      path: '/design-e-presenca-digital-braga'
      fullPath: '/design-e-presenca-digital-braga'
      preLoaderRoute: typeof DesignEPresencaDigitalBragaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redes-wifi-braga': {
      id: '/redes-wifi-braga'
      path: '/redes-wifi-braga'
      fullPath: '/redes-wifi-braga'
      preLoaderRoute: typeof RedesWifiBragaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reparacao-computadores-braga': {
      id: '/reparacao-computadores-braga'
      path: '/reparacao-computadores-braga'
      fullPath: '/reparacao-computadores-braga'
      preLoaderRoute: typeof ReparacaoComputadoresBragaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reparacao-hardware-braga': {
      id: '/reparacao-hardware-braga'
      path: '/reparacao-hardware-braga'
      fullPath: '/reparacao-hardware-braga'
      preLoaderRoute: typeof ReparacaoHardwareBragaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reparacao-portateis-braga': {
      id: '/reparacao-portateis-braga'
      path: '/reparacao-portateis-braga'
      fullPath: '/reparacao-portateis-braga'
      preLoaderRoute: typeof ReparacaoPortateisBragaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApoioEmpresasBragaRoute: ApoioEmpresasBragaRoute,
  DesignEPresencaDigitalBragaRoute: DesignEPresencaDigitalBragaRoute,
  RedesWifiBragaRoute: RedesWifiBragaRoute,
  ReparacaoComputadoresBragaRoute: ReparacaoComputadoresBragaRoute,
  ReparacaoHardwareBragaRoute: ReparacaoHardwareBragaRoute,
  ReparacaoPortateisBragaRoute: ReparacaoPortateisBragaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
